// File: dff.v
// Generated by MyHDL 0.11
// Date: Mon Sep 23 19:36:55 2019


`timescale 1ns/10ps

module dff (
    d,
    f,
    clk
);


output d;
reg d;
input f;
input clk;




always @(posedge clk) begin: DFF_LOGIC
    d <= f;
end

endmodule
